export const SET_GENRE: string = 'SET_GENRE'
export const SET_AUTHOR: string = 'SET_AUTHOR'
export const SET_DATES: string = 'SET_DATE'
export const SEARCH: string = 'SEARCH'
export const FETCH_BOOKS: string = 'FETCH_BOOKS'